spring:
  profiles:
    active:
    - redis

---
spring:
  profiles: redis
  application:
    name: configserver-redis
    
---
spring:
  profiles: mybatis
  application:
    name: configserver-mybatis
  datasource:
  url: jdbc:mysql://127.0.0.1:3306/newer?userSSL=false
  name: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
